apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: simple-docker-build
  labels:
    name: simple-docker-build
spec:
  triggers:
    - type: "GitHub"
      github:
        secretReference:
          name: "github_webhook"
  source:
    git:
      uri: 'https://github.com/openshift-examples/container-build.git'
    contextDir: "docker_build"
  strategy:
    dockerStrategy:
      dockerfilePath: docker_build/Dockerfile
  output:
    to:
      kind: ImageStreamTag
      name: 'simple-docker-build:latest'