apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: simple-docker-build
  labels:
    name: simple-docker-build
spec:
  triggers:
    - type: "GitHub"
      github:
        secretReference:
          name: "github-webhook"
  source:
    git:
      uri: 'https://github.com/M-Ghani97/openshift-piplines.git'
    contextDir: "docker_build/app"
    sourceSecret:
      name: "github-token"
  strategy:
    dockerStrategy:
      dockerfilePath: Dockerfile
  output:
    to:
      kind: ImageStreamTag
      name: 'simple-docker-build:latest'